"x/claim":
  - x/claim/**/*
"x/farming":
  - x/farming/**/*
"x/liquidity":
  - x/liquidity/**/*
"x/liquidstaking":
  - x/liquidstaking/**/*
"x/mint":
  - x/mint/**/*
"x/marketmaker":
  - x/marketmaker/**/*
"x/farm":
  - x/farm/**/*
"c-sync":
  - x/claim/**/*
  - x/farming/**/*
  - x/liquidity/**/*
  - x/liquidstaking/**/*
  - x/mint/**/*
  - x/marketmaker/**/*
  - docs/**/*
  - Makefile
"documentation":
  - docs/**/*
"build":
  - Makefile
  - scripts/*
"ci":
  - buf.yaml
  - .golangci.yml